#!/bin/bash

#Shuffle enrichment script is NOT interchangable with AlignmentPipe Enrichment
ENRICHMENT="/home/chrys/Documents/thesis/data/Pipelines/SHUF/ShuffleEnrichmentUpdated.pl"

#Path to hg19GenomeFile
GENOMEFILE="/media/chrys/HDDUbutuMain/Concat.2272017/hg19GenomeFile"
#Mark
Mark=$1
#SpeciesList
LIST="/media/chrys/HDDUbutuMain/Concat.2272017/Species.Summary.2272017";
#Path to ShuffleTrack -> RepeatMaskerTrack with chr1 start stop family/species 
#cut -f1,2,3,4 RepeatMaskerTrack.Sorted.Cleaned.July17.Indexed.2272017 > ShuffleTrack
SHUFFLETRACK="/media/chrys/HDDUbutuMain/Concat.2272017/ShuffleTrack"

mkdir /media/chrys/HDDUbutuMain/Concat.2272017/Alignments.$Mark/Shuffle.$Mark

DUMMYBED="/media/chrys/HDDUbutuMain/Concat.2272017/Alignments.H4K91ac/H4K91ac.Dummy.bed"
#DUMMYBED="/media/chrys/HDDUbutuMain/Concat.2272017/Alignments.H2AK5ac/H2AK5ac.5Dummy.test.bed"


for (( i = 1; i < 2; i++ )); do
	#statements
	seed=$((1+ RANDOM %30000))
	
	echo "Seed is: $seed"

	#bedtools shuffle -i $DUMMYBED -g $GENOMEFILE > Shuffle.$Mark/$Mark.Shuffled
	bedtools shuffle -seed $seed -i $DUMMYBED -g $GENOMEFILE > /media/chrys/HDDUbutuMain/Concat.2272017/Alignments.$Mark/Shuffle.$Mark/$Mark.Shuffled."${seed}"
	#SHUFFLEBED="$(bedtools shuffle -seed $seed -i $DUMMYBED -g $GENOMEFILE; echo x)"
	#SHUFFLEBED="${SHUFFLEBED%x}"

	bedtools intersect -wo -a /media/chrys/HDDUbutuMain/Concat.2272017/Alignments.$Mark/Shuffle.$Mark/$Mark.Shuffled."${seed}" -b $SHUFFLETRACK |
	cut -f4,8 | awk '{var=$1; split($1,a,".");$1 =a[2];print}' | $ENRICHMENT $LIST > /media/chrys/HDDUbutuMain/Concat.2272017/Alignments.$Mark/Shuffle.$Mark/$Mark.Shuffle."${seed}"

	#rm /media/chrys/HDDUbutuMain/Concat.2272017/Alignments.$Mark/Shuffle.$Mark/$Mark.Shuffled."${seed}"

done



