#!/bin/bash

echo "Path to RepeatMaskerTrack"
read RepTrack


sed -i '1d' $RepTrack

echo "Sorting..."
sort -k6,6 -k7,7n ${RepTrack} -o ${RepTrack}

#Default is less then 100 occurences
echo "Enter Exclusion Threshold"
read Limit

Total=$(wc -l $RepTrack | awk '{print $1}')

cut -f11 $RepTrack > SpeciesList
sort -u SpeciesList > SpeciesUni

for i in $(cat SpeciesUni); 
do
	NAME="$i"
	TYPE=$(grep "$i$" SpeciesList | wc -l); 
	echo $NAME $'\t'$TYPE >> Summary		
done

#rm SpeciesList
#rm SpeciesUni

awk -v var="$Limit" '$2 > var {print}' Summary > Summary.${Limit}

#rm Summary

cut -f1 Summary.${Limit} > List
sort -u List -o List

PROCESSING=${PWD}/ProcessingSub.pl

$PROCESSING $RepTrack $Total

#rm List
echo "Done! Procced to CGP! "

