#!/bin/bash

echo "Specify path to reads."
#read Reads

###EXAMPLE###
#Reads=/media/chrys/HDDUbutuMain/H9CellLine/Aligned/GSM878613.DNAse2/SRR412249.clean.fastq
#Reads=/media/chrys/HDDUbutuMain/H9CellLine/Aligned/GSM605310.H3K36me3/SRR067945.clean.fastq
#Reads=/media/chrys/HDDUbutuMain/H9CellLine/Aligned/GSM605314.H3K4me2/SRR067949.clean.fastq


echo "Specify path to Conncatenated Genome."
#read ConcGenome
ConcGenome=/media/chrys/HDDUbutuMain/Concat.2272017/ConcatenatedGenome.2272017

echo "Specify path to Index file (RepeatMaskerTrack.Indexed)."
#read OriginalIndex

echo "Specify epigenetic mark."
#read Mark
Mark=$1

echo "Creating outoutfolder..."
outDir=$(dirname "${ConcGenome}")
mkdir "$outDir/Alignments.$Mark"
echo "Results will be placed at $outDir/Alignments.$Mark"
jobID=$(basename ${ConcGenome} | tr -dc 0-9)
echo "JobID is $jobID."
echo "Specify path to Index file (RepeatMaskerTrack.Indexed)"

OriginalIndex=$outDir/RepeatMaskerTrack.Sorted.Cleaned.*.Indexed.$jobID

echo "Do you want to sort by Species[S] or SuperFamily[F]?"
#read sortType
#sorting=$(echo "${sortType^^}")
sorting=S

if [[ "$sorting" == "S" ]]
then 
	echo "Selected Species"
	LIST=$outDir/Species.Summary.*

elif [[ "$sorting" == "F" ]] 
then
	echo "Selected SuperFamily"
	LIST=$outDir/Super.Summary.*
else
	echo "Nothing selected,defaulting to species."
	sorting="S"
	LIST=$outDir/Species.Summary.*
fi


echo "Starting up bwa..."

echo "Is the Genome indexed ?[y/n]"
#read check
check=y
checking=$(echo "${check^^}")

if [[ "$checking" == "Y" ]]
then
	echo "Skipping indexing process..."

elif [[ "$checking" == "N" ]]
then
	echo "Starting indexing process..."
	bwa index $ConcGenome
fi

echo "The pipeline can now run unattended all settings been choosen."

echo "Starting alignment..."
time bwa mem -a -t 3 -v 3 $ConcGenome $Reads | samtools view -Sb -o $outDir/Alignments.$Mark/$Mark.bam

echo "Aligment done..."

echo "Doing some converting..."
time samtools sort -@3 $outDir/Alignments.$Mark/$Mark.bam -o $outDir/Alignments.$Mark/$Mark.sorted.bam

echo "Removing unsorted *.bam"
rm $outDir/Alignments.$Mark/$Mark.bam

echo "Indexing *.bam"
time samtools index $outDir/Alignments.$Mark/$Mark.sorted.bam

PipeLoc=$PWD
CONSTRUCTOR=${PWD}/GenomeConstructor.pl

Index=$outDir/MergeIndex.*.bed

echo "Creating a Genome File."
time $CONSTRUCTOR ${ConcGenome} $outDirRepeatMaskerTrack.Sorted.Cleaned.July17.Indexed.2272017

sort -V -k1,1 $outDir/names.txt -o $outDir/names.txt

echo "Resorting the index file to match bam (Can be undone by sort -k1,1 -k2,2n)"
time bedtools sort -faidx $outDir/names.txt -i $Index > $outDir/ResortMergeIndex

echo "Calculating coverage..."
time bedtools coverage -sorted -g $outDir/names.txt -a $outDir/ResortMergeIndex -b $outDir/Alignments.$Mark/$Mark.sorted.bam  > $outDir/Alignments.$Mark/$Mark.Coverage.bed

echo "Creating annotation..."
CONCAT=${PWD}/PostConcat.pl
time bedtools intersect -sorted -g $outDir/names.txt -wo -abam $outDir/Alignments.$Mark/$Mark.sorted.bam  -b $outDir/ResortMergeIndex -bed |
cut -f1,2,3,4,16 |
awk '{var=$4; split($4,a,".");$4 =a[2];print}' | 
$CONCAT $outDir/Alignments.$Mark/$Mark.Coverage.bed > $outDir/Alignments.$Mark/$Mark.Filtered.bed 

echo "Constructing weighted vector..."
COUNT=${PWD}/WeightVector.pl
time $COUNT $outDir/Alignments.$Mark/$Mark.Filtered.bed  > $outDir/Alignments.$Mark/$Mark.ReadWeightVector
VECTOR=$outDir/Alignments.$Mark/$Mark.ReadWeightVector


echo "Reverting IDs to feature annotation and calculating enrichment..."
REVERT=${PWD}/IDReverte.pl
ENRICHMENT=${PWD}/ReadEnrichment.pl

time $REVERT $OriginalIndex $outDir/Alignments.$Mark/$Mark.Filtered.bed | $ENRICHMENT $outDir/Alignments.$Mark/$Mark.Filtered.bed $sorting $VECTOR $LIST

# rm $outDir/Alignments.$Mark/$Mark.Coverage.bed
#cut -f1 $outDir/Alignments.$Mark/$Mark.Filtered.bed > $outDir/Alignments.$Mark/$Mark.ReadList
#cut -f2 $outDir/Alignments.$Mark/$Mark.Filtered.bed > $outDir/Alignments.$Mark/$Mark.IDList
#rm $outDir/Alignments.$Mark/$Mark.Filtered.bed 

echo "Done!"